on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Qmk Build firmware Action
        uses: ijikeman/qmk_build@v0.0.1
        with:
          keyboard: 'lets_split'
          rev: 'rev2'
          keymap: 'macro'

      - name: Qmk Build firmware Action
        uses: ijikeman/qmk_build@v0.0.1
        with:
          keyboard: 'helix'
          rev: 'rev3_4rows'
          keymap: 'macro'

      - name: Qmk Build firmware Action
        uses: ijikeman/qmk_build@v0.0.1
        with:
          keyboard: 'helix'
          rev: 'rev3_4rows'
          keymap: 'default'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ${{ github.workspace }}/output/*.hex
