name: Build QMK Firmware
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Load environmentする為に、一度checkoutする
      - name: Checkout code
        uses: actions/checkout@v4

      # .envファイルを読み込みGITHUB_ENVに設定
      - name: Load environment variables
        run: |
          echo "QMK_BRANCH_NAME=$(grep QMK_BRANCH_NAME .env | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "KEYBOARDS_REV_KEYMAPS=$(grep KEYBOARDS_REV_KEYMAPS .env | cut -d '=' -f2-)" >> $GITHUB_ENV

      - name: confirm env
        run: |
          echo $QMK_BRANCH_NAME
          echo $KEYBOARDS_REV_KEYMAPS

      # qmk_firmwareをcheckout
      - name: Checkout QMK Firmware
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: ${{ env.QMK_BRANCH_NAME }}
          submodules: true

      # qmk_firmware/keyboardsを削除
      - name: Remove existing keyboards directory
        run: rm -rf keyboards

      # qmk_firmware/に自身のリポジトリを./keyboards/として設置(qmk_firmware/keyboards/)
      - name: Checkout My Keyboards
        uses: actions/checkout@v4
        with:
          path: ./keyboards

      # qmk_install.shを実行して依存関係をインストール
      - name: Install dependencies
        run: ./util/qmk_install.sh

      - name: Install qmk
        run:
          pip install qmk

      - name: Setup qmk
        run:
          qmk setup

      - name: confirm env
        run: |
          echo $QMK_BRANCH_NAME
          echo $KEYBOARDS_REV_KEYMAPS

      # qmk compileを実行
      # KEYBOARDS_REV_KEYMAPSには、"keyboard:rev:keymap,keyboard:rev:keymap"の形式で複数指定
      # entryは、"keyboard:rev:keymap"の形式で指定
      # partsは、"keyboard", "rev", "keymap"の形式で分割
      - name: Compile qmk
        run: |
          IFS=',' read -r -a keyboards_rev_keymaps <<< "${{ env.KEYBOARDS_REV_KEYMAPS }}"
          for entry in "${keyboards_rev_keymaps[@]}"; do
            IFS=':' read -r -a parts <<< "$entry"
            keyboard="${parts[0]}"
            rev="${parts[1]}"
            keymap="${parts[2]}"
            qmk compile -kb "$keyboard/$rev" -km "$keymap"
          done

      - name: Confirm builded firmwares
        run: echo $HOME

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: builded-firmwares
          path: .build/*.hex
          include-hidden-files: true # 隠しフォルダで*を指定する為
