name: Build QMK Firmware
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QMK_BRANCH_NAME: ${{ secrets.QMK_BRANCH_NAME }}
      KEYBOARD: ${{ secrets.KEYBOARD }}
      REV: ${{ secrets.REV }}
      KEYMAP: ${{ secrets.KEYMAP }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: ${{ env.QMK_BRANCH_NAME }}
          submodules: true

      - name: Remove existing keyboards directory
        run: rm -rf qmk_firmware/keyboards

      - name: Checkout My Keyboards
        uses: actions/checkout@v4
        with:
          path: qmk_firmware/keyboards
