name: Build QMK Firmware
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .env >> $GITHUB_ENV

      - name: Checkout QMK Firmware
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: ${{ env.BRANCH_NAME }}
          submodules: true

#       - name: Remove existing keyboards directory
#         run: rm -rf qmk_firmware/keyboards

#       - name: Checkout My Keyboards
#         uses: actions/checkout@v4
#         with:
#           path: qmk_firmware/keyboards

#       - name: Install dependencies
#         run: ./util/qmk_install.sh

#       - name: Compile
#         run: ./bin/qmk compile -kb $KEYBOARD$REV -km $KEYMAP

# #      - uses: actions/upload-artifact@v3
# #        with:
# #          name: "$KEYBOARD_$REV_$KEYMAP.hex"
# #          path: ./.build/$KEYBOARD_$REV_$KEYMAP.hex
