name: Build QMK Firmware
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Load environmentする為に、一度checkoutする
      - name: Checkout code
        uses: actions/checkout@v4

      # .envファイルを読み込みGITHUB_ENVに設定
      - name: Load environment variables
        run: cat .env >> $GITHUB_ENV

      # qmk_firmwareをcheckout
      - name: Checkout QMK Firmware
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: ${{ env.QMK_BRANCH_NAME }}
          submodules: true

      # qmk_firmware/keyboardsを削除
      - name: Remove existing keyboards directory
        run: rm -rf keyboards

      # qmk_firmware/に自身のリポジトリを./keyboards/として設置(qmk_firmware/keyboards/)
      - name: Checkout My Keyboards
        uses: actions/checkout@v4
        with:
          path: ./keyboards

      # qmk_install.shを実行して依存関係をインストール
      - name: Install dependencies
        run: ./util/qmk_install.sh

      - name: Install qmk
        run:
          pip install qmk

      - name: Compile
        run:
          qmk setup && qmk compile
          # -kb ${{ env.KEYBOARD }}/${{ env.REV }} -km ${{ env.KEYMAP }}

      - name: Run
        run: ls -al ./.build/

#        - uses: actions/upload-artifact@v4
#        with:
#          name: builded-firmwares
#          path: ./.build/${{ env.KEYBOARD }}_${{ env.REV }}_${{ env.KEYMAP }}.hex
