name: Build QMK Firmware
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .env >> $GITHUB_ENV

      - name: Checkout QMK Firmware
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: ${{ env.QMK_BRANCH_NAME }}
          # submodules: true

      - name: Remove existing keyboards directory
        run: rm -rf keyboards

      - name: Checkout My Keyboards
        uses: actions/checkout@v4
        with:
          path: ./

      # - name: Install dependencies
      #   run: ./util/qmk_install.sh

      - name: Compile
        run:
          ls -al ./ ./keyboards/
      #   run: ./bin/qmk compile -kb ${{ env.KEYBOARD }}/${{ env.REV }} -km ${{ env.KEYMAP }}

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: builded-firmwares
      #     path: ./.build/${{ env.KEYBOARD }}_${{ env.REV }}_${{ env.KEYMAP }}.hex
